project:
  type: website

website:
  title: "Nothing Plain About It"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rplain1
      - icon: mastodon
        href: https://fosstodon.org/@Ryanplain

format:
  html:
    theme: 
      light: zephyr
      dark: vapor
    css: styles.css

editor: source

