project:
  type: website

website:
  title: "Nothing Plain About It"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rplain1

format:
  html:
    theme: pulse
    css: styles.css

editor: source

